### ISSUE TITLE
But I DO want to use it outside of reaction... :(

### ISSUE THREAD

**Issue by mpodlasin** [danielearwicker/computed-async-mobx#20]
![screenshot from 2018-05-10 16-30-05](https://user-images.githubusercontent.com/7916523/39874913-6a4ca172-546f-11e8-828a-648e544982f7.png)

For example in unit tests with `Promise`-returning version of `when`:

![screenshot from 2018-05-10 16-27-03](https://user-images.githubusercontent.com/7916523/39874767-0afc6c48-546f-11e8-9828-eb90b6ce452f.png)

BTW, using callback version of `when` does not work either.
![screenshot from 2018-05-10 16-28-50](https://user-images.githubusercontent.com/7916523/39874834-3ba3ccf6-546f-11e8-81f9-5cbc6db9b590.png)

Same error is thrown. :(

**Comment by ianmstew** [comment]
I have a different scenario, but I also needed to retrieve the value of the `promisedComputed` object outside of a reaction.  Try `userStore.userName.value` instead of `userStore.userName.get()`...  This appears to return the current value of computed object, BUT I doubt that it will trigger potential recomputation-on-get that you gain from `.get()` within a reaction.

**Comment by marjan2k** [comment]
I'm having the same issue with unit testing promisedComputed.

The .value solution works in javascript but doesn't work in typescript.

**Comment by danielearwicker** [comment]
I finally got around to this... the workaround was to use a temporary `autorun` like this:

```ts
let result;
autorun(() => result = thing.get())();
```

But as a convenience for writing unit tests etc I've added this as a built-in helper method called `getNonReactive`. Included in version 4.2.0.
