### ISSUE TITLE
React hook implementation?

### ISSUE THREAD

**Issue by thecodejack** [danielearwicker/computed-async-mobx#26]
Is there any React Hooks implementation of same?

**Comment by danielearwicker** [comment]
I've had good experiences using `useState` to fetch a model object, and the model object is just from a class decorated with `@observable`, `@computed` and `@action` in the usual way. In other words, the hook just avoids the need to decide when to allocate the state object. Otherwise everything works the same as before. Are you thinking of anything else?

**Comment by danielearwicker** [comment]
Though if you're looking for something purely in react hooks (nothing to do with mobx) then I think https://github.com/slorber/react-async-hook/ by @slorber looks pretty cool.

**Comment by thecodejack** [comment]
Cool. `react-async-hook` with `useCallback` probably can power us like this one.
